import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/sections/nav-bar";

export const metadata: Metadata = {
  title: "FE Test Xipat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-colors-bg flex`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
